export const profiles = [
  {
    id: 1,
    name: 'William Dogulas',
    occupation: 'Senior Editor, MIT Tech, London',
    journalistScore: '8.6',
    topAuthor: true,
    tags: [
      'Artificial Intelligence',
      'Machine Learning',
      'Bio Technology',
      'Nano Technology',
      'Data Science',
      'Aerospace',
    ],
    profilePicture: 'https://randomuser.me/api/portraits/men/74.jpg',
  },
  {
    id: 2,
    name: 'Hanna Levin',
    occupation: 'Senior Editor, MIT Tech, London',
    journalistScore: '8.5',
    topAuthor: true,
    tags: [
      'Artificial Intelligence',
      'Machine Learning',
      'Bio Technology',
      'Nano Technology',
      'Data Science',
      'Aerospace',
      'Something',
      'Something',
    ],
    profilePicture: 'https://randomuser.me/api/portraits/women/68.jpg',
  },
  {
    id: 3,
    name: 'Ryan Ekstorm, Bothman',
    occupation: 'Senior Editor, MIT Tech, London',
    journalistScore: '8.3',
    topAuthor: false,
    tags: [
      'Artificial Intelligence',
      'Machine Learning',
      'Bio Technology',
      'Nano Technology',
      'Data Science',
      'Aerospace',
      'Something',
    ],
    profilePicture: 'https://randomuser.me/api/portraits/women/81.jpg',
  },
  {
    id: 4,
    name: 'Adison Torff',
    occupation: 'Senior Editor, MIT Tech, London',
    journalistScore: '7.8 ',
    topAuthor: true,
    tags: [
      'Artificial Intelligence',
      'Machine Learning',
      'Bio Technology',
      'Nano Technology',
      'Data Science',
      'Aerospace',
    ],
    profilePicture: 'https://randomuser.me/api/portraits/men/79.jpg',
  },
  {
    id: 5,
    name: 'Leo Lipshutz',
    occupation: 'Senior Editor, MIT Tech, London',
    journalistScore: '7.8',
    topAuthor: false,
    tags: [
      'Artificial Intelligence',
      'Machine Learning',
      'Bio Technology',
      'Nano Technology',
      'Data Science',
      'Aerospace',
    ],
    profilePicture: 'https://randomuser.me/api/portraits/men/61.jpg',
  },
];
